### ISSUE TITLE
Expression loops

### ISSUE THREAD

**Issue by Kingdaro** [Kingdaro/lunascript#1]
Single-execution expressions and their return values are simple:
```lua
result = do 5 end                             --> result = 5
result = if true then 'pass' else 'fail' end  --> result = 'pass'
```

Loops can return an array with an item for each returned element.
```lua
numbers = for i=1, 10 do i end --> numbers = { 1, 2, ..., 10 }
```

For more complex cases...
```lua
result = while data = getData() do
  if invalidData() then
    return
  end
  data
end
```

Here, `data` at the end of the block is an implicit return. Any executed block will implicitly return its last expression within. With that in mind,

- Does `return` here break out of the loop? Or does it add `nil` to the table and continue?
- When returning `nil`, does it create a hole in the table?
- Should `return` work differently from `return nil`?
- Should a return statement add a value at the end of the array? Or should it halt the loop and set the result variable to the returned value?
- Does returning two values set a table key/value pair, or does it add two values to the end of an array?
  - Additionally, would the language even allow returning more than one value, ignoring the rest when multiple are returned?
- Should a new language construct be added for constructing tables this way?

**Comment by Kingdaro** [comment]
## Proposal: `assign`

For each `assign` in a loop, it does the same as rendering a table pair in a table with the given information. Take this for example:
```lua
nums = for i=1, 3 do
  assign i, i + 1, foo = 'bar'
end
--> first loop:  i = 1, nums = { 1, 2, foo = 'bar' }
--> second loop: i = 2, nums = { 1, 2, foo = 'bar', 2, 3, foo = 'bar' }
--> third loop:  i = 3, nums = { 1, 2, foo = 'bar', 2, 3, foo = 'bar', 3, 4, foo = 'bar' }
```

Note: `foo = 'bar'` inside the loop is redundant. It would simply set `nums.foo` to `'bar'` three times.

More examples:
```lua
letters = for char in "hello":gmatch('.') do
  assign char
end
--> letters = {'h','e','l','l','o'}

hashed = for _,letter in ipairs(letters) do
  assign [letter] = true
end
--> hashed = {
--    ['h'] = true,
--    ['e'] = true,
--    ['l'] = true,
--    ['l'] = true, -- redundant
--    ['o'] = true,
--  }


unpacked = for _,tuple in ipairs{ {1, 2}, {3, 4}, {5, 6} } do
  assign tuple[1], tuple[2]
end
--> unpacked = { 1, 2, 3, 4, 5, 6 }
```

**Comment by Nixola** [comment]
I feel like return shouldn't break the loop, there's ``break`` for that; what if return behaved like assign, and ``break false`` made the whole loop return false?

**Comment by Kingdaro** [comment]
Seems to make the most sense, actually, for `return` to `assign` values to a table, and for `break` to have an optional value to return something on its own. I like that. I'll probably go with that for now.

So with that, I'm guessing a normal `break` on its own would still make the loop return a table, however `break nil` (or `break someNilValue`) would make it return nil? Makes sense.

**Comment by Kingdaro** [comment]
On second thought, I should probably be careful. Creating too many varying language features might make things difficult to document well, which wouldn't be healthy for Luna's simplicity. So... maybe settle for just using break to return a single value from a loop for now, with no more than that. Possibly have another construct for table construction.

**Comment by s-ol** [comment]
`return` has nothing to do with loops and it shouldn't. `break` could accept a parameter that overrides the concatenated loop table but that is just another feature noone needed that strongly. Returning `nil` should leave a hole in the table IMO. You can add a `continue` like in moonscript that skips the index too.

You can deduce whether the loop return value needs to be built at all from the AST.

**Comment by s-ol** [comment]
If you want to stay true to lua you could introduce a multi-line table comprehension syntax that really only does all these things when needed and can have more specific syntax to control it.

**Comment by Kingdaro** [comment]
Table comprehensions will probably be a thing, possibly in place of `n to n [step n]`, though that's another issue.

I was thinking the continue statement could be given a value like `break`, and it'd do the same as `assign` that I've proposed, while skipping iteration at the same time. Two values given can be treated as a key/value pair, one would add it as an array index.

Lots of options for this one, but the most unambiguous solution does seem to be a new keyword. I'll think about it some more when I'm home.
